### PR TITLE
Feature/add company accounts library

### PR DESCRIPTION
**Pull request by leahtaylor**
Add company-accounts-library as dependency in company-accounts-api (line 95)
Format pom file

SFA-530

### CODE REVIEW

**Comment by cburns93** [comment]
I've only just realised that my comment on the other PR about XML being 2 spaces was wrong 👎  .. I do apologise, what I was meant to say was for it to be 4 spaces instead of a tab. My bad :( You can shoot me if you want!

**Comment by leahtaylor** [comment]
Building correctly now @jsimons1989 
http://ch-jenkins-2k8:8080/jenkins/job/Build/job/chs/job/company-accounts.api.ch.gov.uk/job/feature/231/

**Comment by jsimons1989** [comment]
Code is develop should be ready for release which means the company accounts library version needs to be a releasable version not a snapshot version.

**Comment by leahtaylor** [comment]
PR is no longer needed. Filing generator in company accounts api will no longer be using the date helper for mapping. This will now be done in the document generator.

**Pull request closed without merging**
